build for testing

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -6,12 +6,11 @@ on:
   pull_request:
     branches: [ "main", "feature/chrome-history-extension" ]
 
-
 jobs:
   build-and-test:
     defaults:
-        run:
-          working-directory: 'Web Time Machine'
+      run:
+        working-directory: 'Web Time Machine'
     name: Build and Test iOS Safari Extension
     runs-on: macos-latest
 
@@ -21,18 +20,24 @@ jobs:
 
       - name: List all schemes
         run: xcodebuild -list
-      
-      - name: Build Safari Extension
-        run: xcodebuild build -target "Web Time Machine Extension (iOS)" -sdk iphonesimulator OS=17.0
 
-      - name: Test Safari Extension
+      - name: Build Safari Extension for Testing
         run: |
-          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
-            filetype_parameter="workspace"
-            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
+          xcodebuild build-for-testing -scheme "Web Time Machine (iOS)" -sdk iphonesimulator -derivedDataPath './build'
+
+      - name: Test Safari Extension Without Building
+        run: |
+          if [ -d "./build" ]; then
+            if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
+              filetype_parameter="workspace"
+              file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
+            else
+              filetype_parameter="project"
+              file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
+            fi
+            file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
+            xcodebuild test-without-building -scheme "Web Time Machine (iOS)" -"$filetype_parameter" "$file_to_build" -sdk iphonesimulator -derivedDataPath './build'
           else
-            filetype_parameter="project"
-            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
+            echo "Derived data not found, cannot test without building"
+            exit 1
           fi
-          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild test-without-building -scheme "Web Time Machine (iOS)" -"$filetype_parameter" "$file_to_build" -sdk iphonesimulator
